// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AIChat(arg1:backend.AIConfig,arg2:Array<Record<string, string>>):Promise<backend.AIResponse>;

export function Connect(arg1:string):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExecuteCommand(arg1:string,arg2:string):Promise<string>;

export function ExportAllConfig():Promise<void>;

export function FetchModels(arg1:backend.AIConfig):Promise<Array<string>>;

export function GetAIConfig():Promise<backend.AIConfig>;

export function GetConnections():Promise<Array<backend.ConnectionConfig>>;

export function GetServerStats(arg1:string):Promise<Record<string, string>>;

export function ImportAllConfig():Promise<string>;

export function IsConnected(arg1:string):Promise<boolean>;

export function ListRemoteDir(arg1:string,arg2:string):Promise<Array<backend.FileItem>>;

export function MkdirRemote(arg1:string,arg2:string):Promise<void>;

export function RemoveRemote(arg1:string,arg2:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveAIConfig(arg1:backend.AIConfig):Promise<void>;

export function SaveConnection(arg1:backend.ConnectionConfig):Promise<void>;

export function SendTerminalInput(arg1:string,arg2:string):Promise<void>;

export function UploadFile(arg1:string,arg2:string,arg3:string):Promise<void>;
